### PR TITLE
fixed mobile-nav

### PR DESCRIPTION
**Pull request by tanishq-arya**
## What is the change?
I removed a conflicting bootstrap.min.js file

## Related issue?
close: #492 

## How was it tested?
Remove this line and tell us how the code was tested.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.

### CODE REVIEW

**Comment by Pranav016** [comment]
Is the navbar toggle working now ?

**Review by Pranav016 — COMMENTED** [review]
Can you add a screenshot ?

**Comment by tanishq-arya** [comment]
Screenshot (1000)
Screenshot (1001)
Screenshot (1002)
Screenshot (999)

**Comment by Pranav016** [comment]
/level2/

**Comment by Pranav016** [comment]
/gssoc/

**Pull request merged**
