### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by A7abhilash**
## What is the change?
Change in home UI

## Related issue?
#333 

## How was it tested?
Tested thoroughly in localhost

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.

### CODE REVIEW

**Review by Pranav016 — COMMENTED** [review]
change base branch to which you are making a PR to as develop

**Comment by Pranav016** [comment]
/gssoc/

**Comment by shudhanshu03** [comment]
> change base branch to which you are making a PR to as develop
> resolve conflicts

Gs_Develop_Branch 

@A7abhilash Refer this to convert branch it to develop.

**Review by Pranav016 — CHANGES_REQUESTED** [review]
I wanted to merge this PR coz it's ready. I tried resolving the conflicts and trust me it was so hard because conflicts are resolved on basis of branches and you are making a PR from develop to develop. 
I would advice you, do another `git checkout` (create a new branch) from develop and then make a PR from that, name it something other than develop

**Comment by A7abhilash** [comment]
So now i should just create a new branch from develop... And then make a pr to base branch(to develop)?

**Comment by Pranav016** [comment]
> @Pranav016 So now i should just create a new branch from develop... And then make a pr to base branch(to develop)?

Yes that works 👍

**Comment by A7abhilash** [comment]
> > @Pranav016 So now i should just create a new branch from develop... And then make a pr to base branch(to develop)?
> 
> Yes

Ive made a new pr from branch a7abhilash to base branch(develop). #357

**Comment by RushanKhan1** [comment]
Hey @A7abhilash! Thanks for contributing! Actually, there have been some major changes to the code base to fix the bug that was in production also, there are still some more changes that need to be done therefore please **pull the updated code tomorrow** and make a new pr according to that else there will be a lot of merge conflicts.

**Pull request closed without merging**
