### PR TITLE
Added favicon successfully

### PR DESCRIPTION
**Pull request by HarshitAditya27**
## What is the change?
I have added a favicon for the website, code written in header.ejs (code:).The favicon is located in the images folder which is inside the public folder and I have set the value of const URL which is const URL = process.env.URL; (as instructed by you) and one more thing the favicon created is simple it's just the logo with the border of color combination white and pink and I have removed extra lines. I hope you will like my favicon :). (This PR is the updated version of issue no #115 )

## Related issue?
issue: #105 

## How was it tested?
I have tested the website by using the hyper terminal and mongod server.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.
Screenshot (576)_LI

### CODE REVIEW

**Comment by Pranav016** [comment]
Why is the commit message `Added favicon "successfully"`. No need for successfully, and commit messages should be in present tense. Also you did not close your previous PR before making this new PR. Please keep that in mind.

Run these commands to correct commit message and then I'll merge your PR
```
git commit --amend -m "Add Favicon"
git push origin addedfavicon -f
```

**Comment by HarshitAditya27** [comment]
Sir, I have changed the commit message  "Added favicon successfully" to "Add Favicon" as you said :).

**Comment by HarshitAditya27** [comment]
Thanks a lot, sir !!!. Finally, I did my first contribution !!! and thank you for guiding and mentoring me :) :) :) .

**Comment by Pranav016** [comment]
@all-contributors please add @HarshitAditya27 for code

**Comment by Pranav016** [comment]
> Thanks a lot, sir !!!. Finally, I did my first contribution !!! and thank you for guiding and mentoring me :) :) :) .

My pleasure. I hope you were able to learn a lot of things.

**Comment by HarshitAditya27** [comment]
Yes Sir I learned a lot of things under your guidance (thanks a lot for your guidance ) !!! looking forward to more contributions.

**Pull request merged**
