### PR TITLE
ContactUS Formatting

### PR DESCRIPTION
**Pull request by Aayu231**
## What is the change?
Changed the formatting of the contact-us page.

## Related issue?
close: #420

## How was it tested?
Tested thoroughly on local machine.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
BlogSite ss2

### CODE REVIEW

**Review by RushanKhan1 — APPROVED** [review]
Thanks for contributing, I tested your pr and it looks good to me!

**Comment by Aayu231** [comment]
> Thanks for contributing, I tested your pr and it looks good to me!

Thankss

**Comment by Pranav016** [comment]
@RushanKhan1 also add labels if PR is approved

**Comment by Pranav016** [comment]
/gssoc/

**Comment by Pranav016** [comment]
/level2/

**Pull request merged**
