### PR TITLE
Fix Alignment issue on home page. 

### PR DESCRIPTION
**Pull request by prajjwalarora**
## What is the change?
Change is restructuring some code in home.ejs and adding some CSS accordingly. 

## Related issue?
close: #295 

## How was it tested?
Tested via running it on the local machine.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
prev-
110846811-39d5fb80-82d2-11eb-8dd8-900f1ce8a3b6

now-
screencapture-localhost-3000-2021-03-14-02_45_32

### CODE REVIEW

**Comment by Pranav016** [comment]
what are these commits for ?
image

I don't get the last few commits.. I am guessing for resolving conflicts ? Commit message should have been that way..
Also some more conflicts are there ^, please resolve

**Comment by Pranav016** [comment]
Cannot accept so many commits for this small change
image

**Comment by Ankita297** [comment]
Can i work on this ?

**Pull request closed without merging**
