### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by djm-1**
## What is the change?
Code of conduct added.

## Related issue?
issue: https://github.com/ALPHAVIO/BlogSite/issues/17

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes (`[x]`):

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

### CODE REVIEW

**Comment by Pranav016** [comment]
@djm-1  Refer #29 and fix your issues, you've made all the same mistakes.

**Comment by djm-1** [comment]
Hello Sir, I have turned those URLs into hyperlinks. kindly check it.

**Comment by Pranav016** [comment]
There was a reference document in #29 which I wanted you to refer from. A couple of changes required in your PR. Follow this screenshot and make the changes.
image

 I suggest open a new PR from a new branch. You are committing to the master branch and that does not follow the contribution guidelines. And too many commits from adding a code of conduct file. Just do that in one commit and make new PR. 
Happy Learning 🙂

**Comment by Pranav016** [comment]
I am closing the PR for now, you can reopen if you want.

**Pull request closed without merging**
