### PR TITLE
added contact form and route

### PR DESCRIPTION
**Pull request by mis-coder**
Added a contact form on the contact us page. Both frontend and backend are added for the same.
close: #252

Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes [x]:

- [x] Have you followed the Contribution Guidelines while contributing?
- [x] Have you checked there aren't other open Pull Requests for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before 

https://user-images.githubusercontent.com/51118723/111276799-bd3e7680-865d-11eb-9650-f7b6998eddea.mp4

### CODE REVIEW

**Comment by Pranav016** [comment]
/gssoc/

**Review by Pranav016 — COMMENTED** [review]
Good work.
* Dm me the `.env` file on Discord so that I can put it on heroku before merging this PR.
* Change base branch to develop. 
image

**Comment by Pranav016** [comment]
/level2/

**Comment by mis-coder** [comment]
> Good work.
> 
> * Dm me the `.env` file on Discord so that I can put it on heroku before merging this PR.
> * Change base branch to develop.
>   image

thank you and done!

**Pull request merged**
