### PR TITLE
Update gif in readme

### PR DESCRIPTION
**Pull request by innovation-platform**
## What is the change?
I have changed the old gif in the readme to a new gif with the present features of the website.

## Related issue?
close: #378 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## GIF:

blogsitereadme_gif

### CODE REVIEW

**Comment by Pranav016** [comment]
Did you delete the older gif ? If no, can you do that ?

**Comment by innovation-platform** [comment]
Ok I will do that. Thank you.

**Review by Pranav016 — APPROVED** [review]

**Comment by Pranav016** [comment]
/level0/

**Pull request merged**
