### PR TITLE
ContactUs Formatting

### PR DESCRIPTION
**Pull request by Aayu231**
## What is the change?
Changed the formatting of the contact-us page.

## Related issue?
close: #420

## How was it tested?
Tested thoroughly on local machine.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
image

### CODE REVIEW

**Review by Pranav016 — CHANGES_REQUESTED** [review]
Changes look fine but changes have been made to package-lock,json idk why..

Also make the PR from a new branch to master

**Comment by Pranav016** [comment]
closing PR for now, reopen if required.

**Comment by Aayu231** [comment]
okay. Will make the changes as required.

**Comment by Aayu231** [comment]
Heyy, I thought we were supposed to create new branches only for major changes?

**Pull request closed without merging**
