### PR TITLE
Make the input boxes look better and improve placeholder fonts

### PR DESCRIPTION
**Pull request by innovation-platform**
## What is the change?
I have added the border for all the input boxes in the home page and also changed the font-family and font-size and also increased the border-radius of the input boxes.

## Related issue?
issue: #166 

## How was it tested?
It was tested in the localhost:3000 in both google chrome and microsoft edge.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots :
image

### CODE REVIEW

**Review by Pranav016 — CHANGES_REQUESTED** [review]
* Commit messages are really bad, they should be exactly telling what was done in the commit.
* change base branch to develop 

image

**Comment by innovation-platform** [comment]
Sorry for that I will rectify it. Thank You.

**Comment by innovation-platform** [comment]
I just wanted to mention that I am working on this under GSSoC'21. Thank You.

**Comment by Pranav016** [comment]
> I just wanted to mention that I am working on this under GSSoC'21. Thank You.

I think you'll have to make a new PR, your last commit was a just removing a line with wrong messages. Previous commit messages are wrong and are still there in commit history.

**Comment by innovation-platform** [comment]
Ok I will do that. Thank you.

**Pull request closed without merging**
