### PR TITLE
Better version done

### PR DESCRIPTION
**Pull request by aditidewangan**
## What is the change?
I added the better UX for looking good.

## Related issue?
close: #671 

## How was it tested?
yes I was tested it.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x
BlogSite
] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Did you lint your code before making the Pull Request?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.

### CODE REVIEW

**Comment by Pranav016** [comment]
please explain the idea in the issue before making PR, right now the changes are redundant

**Comment by aditidewangan** [comment]
The background color and the text color are same that look very similar and create difficulty to users. I change the text color and it looks good in light mode and make blue color only for light mode and brown for dark mode which gives good UX.

**Comment by Pranav016** [comment]
> The background color and the text color are same that look very similar and create difficulty to users. I change the text color and it looks good in light mode and make blue color only for light mode and brown for dark mode which gives good UX.

Other than the navbar, the font color seems fine..
Navbar font color is also being changed in another issue

**Comment by aditidewangan** [comment]
Yes, If you like the changes than please merge it in the master branch Or have any issue than please comment.

**Review by Pranav016 — COMMENTED** [review]
I don't want to turn things into black and white, for me the color scheme other than the navbar is fine, changes look redundant
image
image

**Pull request closed without merging**
