### PR TITLE
Add confirm Password text box

### PR DESCRIPTION
**Pull request by krishna-y2000**
## What is the change?
Adding confirm password text box

## Related issue?
close: #270 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
image

### CODE REVIEW

**Comment by krishna-y2000** [comment]
@Pranav016 , 
. I have created a new forked project than previous one and applied what you told to change.
There is some conflict please check it . I have not touched this css file . 
Review this and if correct then please merge it.
Thanks.

**Comment by krishna-y2000** [comment]
@Pranav016  
I have resolved the merge conflict.
Please review so i could work on another issue

**Review by Pranav016 — COMMENTED** [review]
Changes look good, I'll merge it in the morning coz my laptop went on an update.

**Comment by Pranav016** [comment]
> Please review so i could work on another issue

You can still work on other issues you are assigned to, just make a new branch from master. 
After this one gets merged you can just pull the changes to that branch..

**Pull request merged**
