### PR TITLE
Issue 294

### PR DESCRIPTION
**Pull request by ankitbiswal547**
## What is the change?
Three dots that were misplaced, that is resolved.
Also the blogs on the home page were having problems with the grid.

## Related issue?
close: #294 

## How was it tested?
Created few blogs and tested all alignment issues.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:

**This is before the changes made:** 
alignment-issue

**This is after the changes**
alignment-issue-resolved

**_In both the above pictures the dots were aligned correctly and conditionally though._**

### CODE REVIEW

**Review by Pranav016 — CHANGES_REQUESTED** [review]
* Why are there changes done to `package-lock.json` ?
* Also last commit message is incorrect. Give clear message about what you did in that commit.
use `git commit --amend -m` to rewrite your last commit message and force push
* change base branch to develop

**Comment by Pranav016** [comment]
/gssoc/

**Comment by RushanKhan1** [comment]
Hey @ankitbiswal547! Thanks for contributing! Actually, there have been some major changes to the code base to fix the bug that was in production also, there are still some more changes that need to be done therefore please **pull the updated code tomorrow** and make a new pr according to that else there will be a lot of merge conflicts.

**Pull request closed without merging**
