### PR TITLE
delete post functionality on each post

### PR DESCRIPTION
**Pull request by mak-ux**
Solves #22

### CODE REVIEW

**Review by Pranav016 — APPROVED** [review]

**Comment by Pranav016** [comment]
I checked the code, seems good. Can you share a screen recording of the working of the feature you added, put it in the comments itself. Since the website isn't deployed yet and I don't have Mongo on my Gitpod so I can't test the feature.

**Comment by mak-ux** [comment]
Sure

**Comment by mak-ux** [comment]
https://user-images.githubusercontent.com/58850584/105352191-9a6e8380-5c13-11eb-8531-c0fd00c0a101.mp4

**Comment by Pranav016** [comment]
>  blog_post_delete.mp4

Excellent work @mak-ux . I am merging this time but just keep in mind next time that work on a new branch before making a PR. Never commit to master and write good commit messages. These are the best practices. Happy Learning!

**Comment by Pranav016** [comment]
@all-contributors please add @mak-ux for code

**Comment by Pranav016** [comment]
@all-contributors please add @mak-ux for code

**Pull request merged**
