### PR TITLE
Added GitHub action to auto merge dependency updates

### PR DESCRIPTION
**Pull request by m-code12**
Fixes: #139

### CODE REVIEW

**Comment by m-code12** [comment]
@Pranav016 review and merge this pr.

**Comment by Pranav016** [comment]
Dependencies are not getting merged automatically..

**Comment by m-code12** [comment]
> Dependencies are not getting merged automatically..

Were these dependencies pr's created after merging this pr?

**Comment by Pranav016** [comment]
@all-contributors please add @m-code12 for code

**Pull request merged**
