### PR TITLE
Header and Footer added

### PR DESCRIPTION
**Pull request by pankajkumarbij**
Header and Footer are added with social media icons.
Header and Footer both are responsive.

Screenshot from 2021-01-22 08-31-12

Solved issue #7

### CODE REVIEW

**Comment by pankajkumarbij** [comment]
Please check it and Merge then I will make a PR for the Pull Request template.

**Comment by Pranav016** [comment]
The Icons and the footer layout is fine but can replace the black color with some linear gradient with a mix of different shades? Choose any color and use background color of the header and the footer as the linear gradient of the shades of that color. Also let the name be BlogSite for now, don't update to daily journal since the logo has been designed with name blogsite. The logo also has to be added to the navbar as a `navbar-icon`. Logo will get merged today so you can use it then

**Comment by Pranav016** [comment]
> Please check it and Merge then I will make a PR for the Pull Request template.

I am closing this PR for now, you can make a new PR or reopen this PR with the request changes.
Now you can first work on the PR template.

**Comment by pankajkumarbij** [comment]
> The Icons and the footer layout is fine but can replace the black color with some linear gradient with a mix of different shades (some bright colors maybe)? Choose any color or search for color pallets for matching shades and use background color of the header and the footer as the linear gradient of the shades of that color. Also let the name be BlogSite for now, don't update to daily journal since the logo has been designed with name blogsite. The logo also has to be added to the navbar as a `navbar-icon`. Logo will get merged today so you can use it then

Ok sir

**Pull request closed without merging**
