### PR TITLE
Updated /posts/:id/edit route 

### PR DESCRIPTION
**Pull request by A7abhilash**
## What is the change?
Enabled the authors to edit the status and category field.
**PS: Ignore commits:  0d9cc84 & 86b761a**

## Related issue?
close: #503 

## How was it tested?
Tested the functionality in localhost.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.

### CODE REVIEW

**Review by Pranav016 — CHANGES_REQUESTED** [review]
squash the commits and then force push

**Comment by A7abhilash** [comment]
> squash the commits and then force push

I didn't get you???

**Comment by Pranav016** [comment]
/gssoc/

**Comment by Pranav016** [comment]
/level2/

**Pull request merged**
