### PR TITLE
style-modified all fonts

### PR DESCRIPTION
**Pull request by mcmonojit**
Modified the fonts of Home page, header, footer, Post preview, Post, About page and Contact page.

## What is the change?
Modified the font style of home page, header, footer, posts, About and contact.

## Related issue?
issue: #113 

## How was it tested?
The app was fully tested after adding the changes in the local machine by following the guidelines given in the Readme. The app worked perfectly without facing any issues.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Screenshot (174)
Screenshot (175)
Screenshot (176)
Screenshot (177)

### CODE REVIEW

**Comment by Pranav016** [comment]
I don't get the whole last word bold thing..

Also I feel that this definitely needs to be changes, rest everything is formal but this heading looks like a chalk font. Could be better-
image

**Comment by mcmonojit** [comment]
@Pranav016 , the changes you proposed have been made in the new commit. Take a look.
Screenshot (181)
Screenshot (180)
Screenshot (182)

**Review by Pranav016 — CHANGES_REQUESTED** [review]
Code looks fine. There are some merge conflicts that need to be resolved. I'd suggest you resolve conflicts on your local system by pulling master, then make a new pull request with just one commit because there are a few redundant commits in this PR like changing URL. Commit history needs to be clean. Also the base branch isn't develop as mentioned in contribution guidelines.

**Comment by Pranav016** [comment]
I am closing this for now, reopen if needed. Also if you are making a new PR, better fonts can also be tried.

**Comment by mcmonojit** [comment]
Ok. I have made a new PR #130  .  Please have a look.

**Pull request closed without merging**
