### PR TITLE
Added /author/:id route

### PR DESCRIPTION
**Pull request by A7abhilash**
## What is the change?
Added a new route /author/:id route where users can view other user's profile and thier blogs

## Related issue?
close: #436 

## How was it tested?
Tested the functioning and responsiveness thoroughly in localhost.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.

### CODE REVIEW

**Comment by Pranav016** [comment]
/gssoc/

**Comment by Pranav016** [comment]
/level2/

**Comment by Pranav016** [comment]
Will the author be visible when I click Read More ?

**Comment by A7abhilash** [comment]
> Will the author be visible when I click Read More ?

You mean to ask, in the /posts/:postId route ? 
Well i havent added the link to the author there... I raise another issue and make a pr for improving UI of that route... So there ill add the link to the author.

**Comment by Pranav016** [comment]
> > Will the author be visible when I click Read More ?
> 
> You mean to ask, in the /posts/:postId route ?
> Well i havent added the link to the author there... I will raise another issue and make a pr for improving UI of that route... So there ill add the link to the author.

Yes I was for `/posts/:postId route`. 
Yeah works for me, you can do it in the next PR

**Review by Pranav016 — APPROVED** [review]

**Pull request merged**
