### PR TITLE
[UI]:Logo redirects to home

### LINKED ISSUE #586: [redirect] Logo redirect to home page
### **To Reproduce**

1. Go to 'https://alphavio-daily-journal.herokuapp.com/'
2. Click on `'Daily journal logo'`

### **Solution**
On clicking on the logo it should redirect to home page

### **Screenshots**
Screenshot (40)_LI

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

### PR DESCRIPTION
**Pull request by Aryamanz29**
## What is the change?
Logo now redirect to home page

## Related issue?
Closes: #586 

## How was it tested?
Tested locally, works as expected.

## Checklist:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Screenshot (45)
Screenshot (46)
Screenshot (47)

### CODE REVIEW

**Review by RushanKhan1 — APPROVED** [review]
I tested your pr and it looks good to me. Good work!

**Comment by Pranav016** [comment]
/gssoc/

**Comment by Pranav016** [comment]
@RushanKhan1 also add labels when approving 👍

**Comment by Pranav016** [comment]
/level2/

**Pull request merged**
