### PR TITLE
Improved UI/UX home design 

### PR DESCRIPTION
**Pull request by Ankita297**
## What is the change?
Improved UI/UX home design 
## Related issue?
issue: #159 

## How was it tested?
I checked it in my local system.
## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Daily Journal - Google Chrome 08-03-2021 19_42_35 (2)

### CODE REVIEW

**Comment by AnanyaNegi** [comment]
Hi @Ankita297, I reviewed your code. Can you make a gif considering the new UI/UX you have designed?

**Comment by AnanyaNegi** [comment]
Hi @Ankita297, I reviewed your code. Can you make a gif displaying the new UI/UX you have designed?

**Comment by Ankita297** [comment]
okay mam . I will do it .

**Comment by Ankita297** [comment]
So sir do i still need to create the gif or not ?

**Comment by Pranav016** [comment]
/gssoc/

**Pull request merged**
