### PR TITLE
Aligned dark mode button to bottom left corner

### PR DESCRIPTION
**Pull request by Abhijay007**
## What is the change?
I improved the alignment of the dark mode button and removed unnecessary code from the codebase

***before***
dark-mode

***after***
darkmode

***Now What is mean by unnecessary code ?***
The dark mode.js is defined two times in the codebase both in app.js and footer.ejs which causes an alignment issue but I fixed that

## Related issue?
issue: #114 Align dark mode button to bottom left corner

## How was it tested?
I tested the code by running it on my localhost and also test its responsiveness and other parameters using the chrome inspect element.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you tested the code before submission?

### CODE REVIEW

**Comment by Abhijay007** [comment]
@Pranav016 sir pakage.json file is changed just because of node modules I install those are just version upgrades.

**Comment by Pranav016** [comment]
> @Pranav016 sir pakage.json file is changed just because of node modules I install those are just version upgrades.

I know they are version upgrades, but they are not required right now. We upgrade version after testing that it works perfectly on that version. We use a bot to upgrade our versions automatically, don't worry about version upgrades.

**Comment by Abhijay007** [comment]
> > @Pranav016 sir pakage.json file is changed just because of node modules I install those are just version upgrades.
> 
> I know they are version upgrades, but they are not required right now. We upgrade version after some testing that it works perfectly on that version. We use a bot to upgrade our versions automatically if outdated, don't worry about version upgrades.

So, sir can you please avoid this package .json file or delete this file from my commits as you have maintainer access.
Because I don't know how to revert these updates as they come with node modules.

**Comment by Pranav016** [comment]
> > > @Pranav016 sir pakage.json file is changed just because of node modules I install those are just version upgrades.
> > 
> > 
> > I know they are version upgrades, but they are not required right now. We upgrade version after some testing that it works perfectly on that version. We use a bot to upgrade our versions automatically if outdated, don't worry about version upgrades.
> 
> So, sir can you please avoid this package .json file or delete this file from my commits as you have maintainer access.
> Because I don't know how to revert these updates as they come with node modules.

I don't have to access to your commits..
What you can do is roll-back to a previous commit or go back to master and start working on a new branch.

**Comment by Abhijay007** [comment]
> I don't have to access to your commits..
> What you can do is roll-back to a previous commit or go back to master and start working on a new branch.
> Make sure to update your local master with the upstream master before working.

Sir, but the point is that even after I roll back those commits and start working from the beginning I need to install node modules which affect this whole `package.json` file because node modules come with these versions I didn't install them intentionally those versions just comes with node modules.

**Comment by Pranav016** [comment]
> > I don't have to access to your commits..
> > What you can do is roll-back to a previous commit or go back to master and start working on a new branch.
> > Make sure to update your local master with the upstream master before working.
> 
> Sir, but the point is that even after I roll back those commits and start working from the beginning I need to install node modules which affect this whole `package.json` file because node modules come with these versions I didn't install them intentionally those versions just comes with node modules.

just do `npm i` and it won't affect any versions

**Comment by Abhijay007** [comment]
> > > I don't have to access to your commits..
> > > What you can do is roll-back to a previous commit or go back to master and start working on a new branch.
> > > Make sure to update your local master with the upstream master before working.
> > 
> > 
> > Sir, but the point is that even after I roll back those commits and start working from the beginning I need to install node modules which affect this whole `package.json` file because node modules come with these versions I didn't install them intentionally those versions just comes with node modules.
> 
> just do `npm i` and it won't affect any versions

ok, I will try

**Comment by Pranav016** [comment]
> go back to master and start working on a new branch.
> Make sure to update your local master with the upstream master before working.

Do this, there are too many commits in this PR and too many changes, more than what were mentioned in the issue. The last commit message is also incorrect.

**Comment by Pranav016** [comment]
I am closing this PR for now, reopen if needed.

**Pull request closed without merging**
