### PR TITLE
Added github action

### PR DESCRIPTION
**Pull request by Abhijay007**
## What is the change?
 Added GitHub actions to greet first-time contributors

## Related issue?
issue: #123 

## How was it tested?
locally by contributor

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?

### CODE REVIEW

**Comment by Pranav016** [comment]
If I raise an issue or a new PR (obviously not a new contributor), does it still display the same message ? `Hi, thanks for creating your first issue at BlogSite`

**Comment by Abhijay007** [comment]
> If I raise an issue or a new PR (obviously not a new contributor), does it still display the same message ? `Hi, thanks for creating your first issue at BlogSite`

No, @Pranav016 sir, it is only for new contributors, I think we need to add another workflow for that. 
we can raise a separate issue for that task.

**Comment by Pranav016** [comment]
> > If I raise an issue or a new PR (obviously not a new contributor), does it still display the same message ? `Hi, thanks for creating your first issue at BlogSite`
> 
> No, @Pranav016 sir, it is only for new contributors, I think we need to add another workflow for that.
> we can raise a separate issue for that task.

Oh ok, I got it. You're using pre-made actions from GitHub, it'll detect only new comers. 👍 

Also what GitHub token do I need to add to the secrets file? You have used secrets.GithubToken

**Comment by Abhijay007** [comment]
> > > If I raise an issue or a new PR (obviously not a new contributor), does it still display the same message ? `Hi, thanks for creating your first issue at BlogSite`
> > 
> > 
> > No, @Pranav016 sir, it is only for new contributors, I think we need to add another workflow for that.
> > we can raise a separate issue for that task.
> 
> Oh ok, I got it. You're using pre-made actions from GitHub, it'll detect only new comers. 👍
> 
> Also what GitHub token do I need to add to the secrets file? Since you used secrets.GithubToken

@Pranav016  sir github_token secret provides Authentication in a workflow means we gave access to this workflow every time it wants to access our repo. you can read more about it here https://docs.github.com/en/actions/reference/authentication-in-a-workflow.

and yeah we can also make a workflow to greet existing contributors but we may need to change these two part of the code:
```
on: [pull_request, issues]

- uses: actions/first-interaction@v1

````
`on` is for a task like on what thing you need to apply this and in  `uses` we define actions and its version, there are several other actions so may there is something to greet existing contributors also. 

but I don't know about that action if its exisits or not.

**Comment by Pranav016** [comment]
I think you got me wrong, I know how it works.
You just used pre-made action from actions repo by GitHub `uses: actions/first-interaction@v1` like this. 

What I was asking is you used this `repo-token: ${{ secrets.GITHUB_TOKEN }}` . This means you access GitHub token from secrets file so do I need to add a token to it?

**Comment by Pranav016** [comment]
I think I'll merge it for now then I'll manage the GitHub token, don't worry. But a small think I noticed that your hyperlinks are incorrect. 
Do it like this.
```
[Contribution guidelines](link here)
```

**Comment by Abhijay007** [comment]
> I think I'll merge it for now then I'll manage the GitHub token, don't worry. But a small think I noticed that your hyperlinks are incorrect.
> Do it like this.
> 
> ```
> [Contribution guidelines](link here)
> ```

@Pranav016 sir, Done with the changes

**Comment by Pranav016** [comment]
Also I'll advise you one thing, make a new branch and then make a PR to develop branch. Don't commit directly to develop..
I'll tell you later what could be downsides of committing directly to the branch you want to make a PR on.

**Comment by Pranav016** [comment]
@all-contributors please add @Abhijay007 for code

**Pull request merged**
