### PR TITLE
Add CKEditor

### PR DESCRIPTION
**Pull request by luckykumarirai**
## What is the change?
Add CKEditor instead of textarea that provide flexibility to change the font style of content, add images and tables.

## Related issue?
issue: #205 

## How was it tested?
I have tested it in my local system.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Screenshot from 2021-02-22 20-24-17

### CODE REVIEW

**Review by Pranav016 — CHANGES_REQUESTED** [review]
New PRs got merged so there are some merge conflicts. I'll test the code after they are resolved. 👍

**Comment by luckykumarirai** [comment]
> New PRs got merged so some merge conflicts have risen. I'll test the code after they are resolved.

@Pranav016 I have resolved the conflicts now you can test.

**Review by Pranav016 — APPROVED** [review]
Right now I am merging the PR based on the demo in #165

**Comment by Pranav016** [comment]
@all-contributors please add @luckykumarirai for code

**Comment by Pranav016** [comment]
@luckykumarirai the build for the website is failing after this PR.

**Comment by luckykumarirai** [comment]
@Pranav016  what do I have to do for solving this problem?

**Comment by Pranav016** [comment]
> @Pranav016 what do I have to do for solving this problem?
> Because I have not made changes in any other files except 2 or 3 files.

Right now I took care of it 👍 Took a couple of hours.
Will let you know if any other help is required.

**Pull request merged**
