### PR TITLE
Added search functionality

### LINKED ISSUE #14: Add functionality to search articles by title on the home page.

### PR DESCRIPTION
**Pull request by sahilsaha7773**
Fixes #14 
### Preview
search_functionality

### CODE REVIEW

**Comment by Pranav016** [comment]
Great Job!

**Comment by sahilsaha7773** [comment]
> Great Job!

Thanks!

**Comment by Pranav016** [comment]
@all-contributors please add @sahilsaha7773 for code

**Comment by Pranav016** [comment]
@all-contributors please add @sahilsaha7773 for code

**Pull request merged**
