### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ANSHIKA1806**
@Pranav016  
Sir, I've updated both the links on README file. Please check it and let me know if more changes are required or accept my pull request.
THANK YOU.

### CODE REVIEW

**Comment by Pranav016** [comment]
/gssoc/

**Comment by Pranav016** [comment]
/level1/

**Comment by Pranav016** [comment]
@ANSHIKA1806 please tag issue number here

**Comment by ANSHIKA1806** [comment]
ISSUE NUMBER #445

**Pull request merged**
