### PR TITLE
fix(blog-post): fixed the system for adding images to blogpost

### PR DESCRIPTION
**Pull request by priyanshu20**
## What is the change?
The photo saving method was broken fixed
* Post.ejs template
* Compose Router
* GetPost Router

## Related issue?
close: #485 

## How was it tested?
Using the client app

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.

### CODE REVIEW

**Review by RushanKhan1 — APPROVED** [review]
I tested your pr and it looks good to me. Good work!

**Comment by Pranav016** [comment]
Are we able to submit post without storing an image ?

**Comment by priyanshu20** [comment]
Yes we can submit post without an image.

**Comment by Pranav016** [comment]
/gssoc/

**Comment by Pranav016** [comment]
/level2/

**Pull request merged**
