### PR TITLE
Documentation update

### PR DESCRIPTION
**Pull request by ankitgoel25**
## What is the change?
Grammar fixes in documentation.

## Related issue?
issue: None

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

### CODE REVIEW

**Review by Pranav016 — COMMENTED** [review]
Thank you for contributing, I would have liked if you'd have committed on a new branch instead of master but since you're a beginner, I'll merge this after adding relevant tags. I'll add the tags tomorrow since girlscript team will be sending the official tags to us tomorrow.

**Comment by ankitgoel25** [comment]
Okay, I'll keep it in mind for the next time. Thank you for reviewing my PR.

**Comment by Pranav016** [comment]
/level0/
/gssoc/

**Comment by Pranav016** [comment]
/gssoc/

**Pull request merged**
