### PR TITLE
Added favicon

### PR DESCRIPTION
**Pull request by HarshitAditya27**
## What is the change?
I have added a favicon for the website, code written in header.ejs (code:<link rel="icon" href="/images/favicon.ico">).The favicon is located in the images (which is created by me) folder which is inside the public folder and I have also changed the value const URL which is const URL = "mongodb://localhost:27017/blogDB"; (as you said) and one more thing the favicon created is simple it's just the logo with the border of color combination white and pink. I hope you will like my favicon :). 

## Related issue?
issue: #105

## How was it tested?
I have tested the website by using the hyper terminal and mongod server.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Screenshot (572)_LI

### CODE REVIEW

**Comment by Pranav016** [comment]
* `"mongodb://localhost:27017/blogDB"` this is only used for testing on your local system.
* Add the favicon to assets folder
* Change base branch to develop, follow the Contribution guidelines mentioned in [CONTRIBUTING.md](CONTRIBUTING.md)

**Comment by Pranav016** [comment]
This is how you change base branch
image

**Comment by HarshitAditya27** [comment]
Sir, I have changed the destination of favicon to assets folder but I can't access favicon as it now not available in the static (public) folder and I have tried many ways to access favicon but I cant access it, sir can you please help where  I am going wrong?

**Comment by Pranav016** [comment]
> Sir, I have changed the destination of favicon to assets folder but I can't access favicon as it now not available in the static (public) folder and I have tried many ways to access favicon but I cant access it, sir can you please help where I am going wrong?

I don't get it? You can't access it?
If you're a beginner I understand, I'd advise you to close this PR. Make a new branch from main and then add your changes and make a new PR.

**Comment by HarshitAditya27** [comment]
Sir can I put the favicon inside the public folder because from there I can display it on the website using the HTML  tag but when the favicon is inside the assets then my HTML tag is not working.

**Comment by Pranav016** [comment]
> Sir can I put the favicon inside the public folder because from there I can display it on the website using the HTML tag but when the favicon is inside the assets then my HTML tag is not working.

You have to change the path for 

> Sir can I put the favicon inside the public folder because from there I can display it on the website using the HTML tag but when the favicon is inside the assets then my HTML tag is not working.

You have to change the path in link tag.

**Comment by HarshitAditya27** [comment]
Sir I did that but it's not working (favicon is located at assets folder).

**Comment by Pranav016** [comment]
> Sir I did that but it's not working (favicon is located at assets folder).

Then it is incorrect

**Comment by HarshitAditya27** [comment]
Sir this is the tag I used <link rel="icon" href="assets/favicon.ico">.I have located this tag under the header.ejs file. Now can you tell me where I am going wrong and what should be the correct path?

**Comment by HarshitAditya27** [comment]
Sir, I have sent the screenshot of html tag which I am using. 
Screenshot (573)_LI
Sir now can you tell me where I am going wrong and what should be the correct path?

**Comment by Pranav016** [comment]
> Sir, I have sent the screenshot of html tag which I am using.
> Screenshot (573)_LI
> Sir now can you tell me where I am going wrong and what should be the correct path?

This is not the correct path.

**Comment by Pranav016** [comment]
I'll let you know the correct path after my class gets over.
Try this till then, try using this for setting favicon. Just update the path according to our project-
`app.use('/favicon.ico', express.static('images/favicon.ico'));`

**Comment by HarshitAditya27** [comment]
OK sir :)

**Comment by HarshitAditya27** [comment]
sir, correct path?

**Comment by Pranav016** [comment]
> Sir, correct path?

You still couldn't figure out?

**Comment by Pranav016** [comment]
Since we used public folder for static files `app.use(express.static("public"));`

Add an images folder to public, store the favicon there and add this tag to the header.ejs.
```
<link rel="icon" href="/images/favicon.ico">
```
There are other methods to do this but since you're a beginner, this method will be easier 🙂

**Comment by HarshitAditya27** [comment]
Ok, sir got it. Thank you

**Comment by HarshitAditya27** [comment]
Sir one last question I am having  problem with editing so can I close this PR and create a new one and I will push my work to your develop repository?

**Comment by Pranav016** [comment]
> Sir one last question I am having problem with editing so can I close this PR and create a new one and I will push my work to your develop repository?

Don't push it to develop, push your changes to a new branch and when making a PR change base branch to develop. Refer to screenshot sent above to see how change base branch while making PR.

**Pull request closed without merging**
