### PR TITLE
Number of views functionality added

### PR DESCRIPTION
**Pull request by aniketlodh**
## What is the change?
Number of views added that shows how many users have visited the blog.

## Related issue?
close: #244 

## How was it tested?
Tested it on my local machine and it worked fine.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Did you lint your code before making the Pull Request?
- [] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:

https://user-images.githubusercontent.com/55927827/114207300-dcd57000-9979-11eb-854e-1495bacbffb4.mp4

### CODE REVIEW

**Comment by aniketlodh** [comment]
Hey, @Pranav016, Is it possible to increase the level of this PR to round off the previous PR since that didn't have the labels.

**Comment by Pranav016** [comment]
> Hey, @Pranav016, Is it possible to increase the level of this PR to round off the previous PR since that didn't have the labels.

But I did add labels to that PR? 
Labels added exactly when PR is made doesn't matter, the PR just needs to have labels to get detected.

**Comment by aniketlodh** [comment]
> > Hey, @Pranav016, Is it possible to increase the level of this PR to round off the previous PR since that didn't have the labels.
> 
> But I did add labels to that PR?
> Labels added exactly when PR is made doesn't matter, the PR just needs to have labels to get detected.

I just now checked my score. They have now detected that PR successfully. Maybe later when you added the labels, they have detected. Sorry to bother you.

**Comment by aniketlodh** [comment]
Is this PR ok or do I need to do something?

**Review by Pranav016 — APPROVED** [review]

**Comment by Pranav016** [comment]
/gssoc/

**Comment by Pranav016** [comment]
/level2/

**Pull request merged**
