### PR TITLE
[UI] Update Login/Signup forms

### LINKED ISSUE #335: [UI] Improve Current UI of login/Signup  Forms
### Feature request-
Need improvement in the current UI of login/signup forms of the website.

### Is your feature request related to a problem? Please describe. (optional)
As of now, we see that the text size/font-color of the forms are not that up to mark and it needs style improvement, Such that it becomes more interactive to users.

### Describe the solution you'd like
Using Bootstrap and another frontend library we can improve its design.

### Describe how this feature will be useful to our readers.
Better UI helps in engaging more users to the website.

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

### PR DESCRIPTION
**Pull request by Aryamanz29**
Fixes #335

## What is the change?
Update Login and Signup form UI and combine it into a single file `(ie.BlogSite/views/logIn.ejs)` and remove `BlogSite/views/signUp.ejs`.Since both logIn.ejs and signUp.ejs have similar form template. Also done some necessary changes in `BlogSite/routes/user.router.js` such that it works work same as before.

## Related issue?
close: #335 

## Video (Pls ignore colors in the video they might get altered by screen rec):  
https://user-images.githubusercontent.com/56113566/111092318-bb8c8a00-855b-11eb-8876-4501f992d615.mp4

## How was it tested?
Tested Locally works same as before. The user successfully registered into the database.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:

Screenshot from 2021-03-15 05-43-39
Screenshot from 2021-03-15 05-44-06
Screenshot from 2021-03-15 05-44-11

## Forms in Dark mode:

Screenshot from 2021-03-15 05-44-24
Screenshot from 2021-03-15 05-44-39

## Front Page with a blog post:

Screenshot from 2021-03-15 06-29-13

### CODE REVIEW

**Comment by Aryamanz29** [comment]
Kindly add the` Gssoc` label to this PR @Pranav016  @AnanyaNegi

**Comment by Pranav016** [comment]
/GSSoC/

**Comment by Pranav016** [comment]
Looks really good, one question. Is it optimized for mobile devices ?
If not, can you create a new issue after this PR is merged to optimize it for mobile ?

**Review by Pranav016 — APPROVED** [review]

**Comment by Aryamanz29** [comment]
> Looks really good, one question. Is it optimized for mobile devices ?
> If not, can you create a new issue after this PR is merged to optimize it for mobile ?

Yes it is optimised for mobile devices 😁

**Pull request merged**
