### PR TITLE
Margin under nav-bar #232

### PR DESCRIPTION
**Pull request by NehaK745**
## What is the change?
Margin under nav-bar 

## Related issue?
issue:  #232

### CODE REVIEW

**Comment by Pranav016** [comment]
Can you add a screenshot reflecting the changes you made ?

**Comment by Pranav016** [comment]
This issue is already assigned to someone else..

**Comment by NehaK745** [comment]
Screenshot (1)

**Comment by NehaK745** [comment]
Thankyou :)

**Pull request closed without merging**
