### PR TITLE
Added 3 logo choices (for Light and Dark Mode)

### PR DESCRIPTION
**Pull request by anubhab1710**
Fulfilled Step-1 of Issue #11 

**Added:**
* 3 logo choices with their variation in both Light and Dark Mode (In PNG format) - all files in the assets folder
_Kindly review the same and select a logo so that I can proceed with Step 2 for updating the Readme banner_

Showcase

### CODE REVIEW

**Comment by Pranav016** [comment]
I like the 2nd logo. I would like to know your opinion as well!
Also do you think the name BlogSite should be changed to something better?

**Comment by anubhab1710** [comment]
> I like the 2nd logo. I would like to know your opinion as well!
> Also do you think the name BlogSite should be changed to something better?

I would also prefer the 2nd logo! And we can surely change the name if you want, since you are the creator of the project, something that might suit the logo too. 

Also, do I need to create a new pull request after updating the banner?

**Comment by anubhab1710** [comment]
@Pranav016 Maybe we can go with the name "Scribble" for the blog site as it gives an insight of what the project is for.

**Comment by Pranav016** [comment]
> @Pranav016 Maybe we can go with the name "Scribble" for the blog site as it gives an insight of what the project is for.

I'll not be changing name rn, maybe sometime in the future. I'll merge your branch after my class gets over, you can work on the banner till then. 2nd logo👍

**Comment by Pranav016** [comment]
> @Pranav016 Maybe we can go with the name "Scribble" for the blog site as it gives an insight of what the project is for.

I'll not be change name rn, maybe some time later. You can start working on the banner now with 2nd logo ( light ). When you commit the banner, I'll merge the PR

**Comment by Pranav016** [comment]
@anubhab1710 Issue closed?

**Comment by anubhab1710** [comment]
> @anubhab1710 Issue closed?

I am making a new pull request right now

**Comment by anubhab1710** [comment]
I have made a new Pull Request with the changes. Please check

**Pull request closed without merging**
