### PR TITLE
dependabot auto merge added

### PR DESCRIPTION
**Pull request by pankajkumarbij**
## What is the change?
A new file added dependabot.yml to auto-merge GitHub action. 

## Related issue?
issue: #139 

## How was it tested?
NA

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
NA

### CODE REVIEW

**Comment by pankajkumarbij** [comment]
I am a participant in mexili winter of code and jwoc both.

**Comment by Pranav016** [comment]
> I am a participant in mexili winter of code and jwoc both.

I don't know if I can give you points for both for a single issue because for MWoC I have to add a label on the PR and for JWoC as well I have to submit your PR links and there would be label for MWoC if you are working under that..

Let me know which one you want me to give you points for.

**Comment by Pranav016** [comment]
Also one more thing, next time work on a new branch instead of master and change base branch to develop while making the PR.

**Comment by pankajkumarbij** [comment]
> Also one more thing, next time work on a new branch instead of master and change base branch to develop while making the PR.
> 
> image

Sorry, I forgot to change the branch by mistake.

I have a participant in both JWOC and MWOC but if you can only give marks in one program then I want to go with  MWOC.

**Comment by pankajkumarbij** [comment]
If you can give both JWOC and MWOC then please add both programs.

**Comment by Pranav016** [comment]
> If you can give both JWOC and MWOC then please add both programs.

I would if I could, I have to put 1 tag on the issue so I am putting MWoC. Also I have to submit PR links and they check them..

**Comment by Pranav016** [comment]
@pankajkumarbij  Also I don't think auto merge action was added for all-contributors bot?

**Comment by pankajkumarbij** [comment]
> @pankajkumarbij Also I don't think auto merge action was added for all-contributors bot?
> 
> Also did you test this before making the PR? Was it working?
> 
> I don't see how will it merge dependabot PRs, let me know then I'll add the points

Sorry
Yes, it not for all contributors.
I reverting this PR and make another PR.

**Comment by pankajkumarbij** [comment]
> @pankajkumarbij Also I don't think auto merge action was added for all-contributors bot?
> 
> Also did you test this before making the PR? Was it working?
> 
> I don't see how will it merge dependabot PRs, let me know then I'll add the points

Sorry, It not works for all contributors you can delete this file and add merge the new pull request.

**Comment by Pranav016** [comment]
> > @pankajkumarbij Also I don't think auto merge action was added for all-contributors bot?
> > Also did you test this before making the PR? Was it working?
> > I don't see how will it merge dependabot PRs, let me know then I'll add the points
> 
> Sorry, It not works for all contributors you can delete this file and add merge the new pull request.

I think it doesn't work for dependabot Pull requests as well.
Dependabot pull request are open but they are not getting merged.

**Pull request merged**
