### PR TITLE
Added like functionality.

### PR DESCRIPTION
**Pull request by aniketlodh**
## What is the change?
Added like functionality that didn't work previously. Users can now like the blogs they like.

## Related issue?
close: #560 

## How was it tested?
Tested it on my local computer and worked fine.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:

https://user-images.githubusercontent.com/55927827/113485040-4280b280-94c9-11eb-90fd-b02069ebfc87.mp4

### CODE REVIEW

**Review by Pranav016 — CHANGES_REQUESTED** [review]
change base branch to master.

Also there are changes in the package-lock.json file but I understand, issue corresponding to that has already been raised..
#497

**Comment by Pranav016** [comment]
/gssoc/

**Comment by Pranav016** [comment]
/level2/

**Comment by aniketlodh** [comment]
@Pranav016  you mean i should make the PR to master branch of this repo?
I haven't made any changes in the lock file. Those changes were made automatically when i ran "npm install". So i think the already raised issue you are talking addresses some other issue in the file.

**Comment by aniketlodh** [comment]
Do I need to change this to master?
IMG_20210404_093115

**Comment by Pranav016** [comment]
> @Pranav016 you mean i should make the PR to master branch of this repo?
> I haven't made any changes in the lock file. Those changes were made automatically when i ran "npm install". So i think the already raised issue you are talking addresses some other issue in the file.

No, it's fine. Basic issue with lockfile version. Nothing serious

**Comment by Pranav016** [comment]
> Do I need to change this to master?
> IMG_20210404_093115

Yes

**Comment by aniketlodh** [comment]
Is this fine or do I need to do anything else?

**Comment by aniketlodh** [comment]
Hi @Pranav016, Could you please tell me whether I need to do anything else?

**Comment by Pranav016** [comment]
> Hi @Pranav016, Could you please tell me whether I need to do anything else?

Resolve conflicts

**Comment by aniketlodh** [comment]
okay, I'm generating a new PR resolving the conflicts. Please close this one.

**Pull request closed without merging**
