### PR TITLE
Custom Scrollbar Added

### PR DESCRIPTION
**Pull request by DEEPIKA-SUK**
## What is the change?
I have added Custom Scrollbar to the website.

## Related issue?
close: #579

## How was it tested?
I have locally tested this by running on my desktop.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [ ] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Screenshot (138)_LI
Screenshot (139)_LI

### CODE REVIEW

**Review by RushanKhan1 — CHANGES_REQUESTED** [review]
@DEEPIKA-SUK Thanks for contributing!
I tested your pr, the scrollbar looks nice but it doesn't show up on mobile devices. Please fix.

Screenshot from 2021-04-04 22-39-16

**Comment by DEEPIKA-SUK** [comment]
@RushanKhan1 I have tried a lot to add for mobile view but it doesn't work and I have also searched on internet, but I could not find any resources also for that, and I have also seen many other Gssoc'21 projects where this feature was added but in those also, scroll bar is not visible in mobile view. Kindly guide me what should I do now.
Thank you.

**Comment by Pranav016** [comment]
@RushanKhan1 you can merge this 👍 
@DEEPIKA-SUK But I was thinking that should we make the scrollbar fully blue for light mode ? and fully orange for dark mode ?

In light mode only search button is orange and that too is going to be changed to blue very soon after the PR for it gets merged. So the whole theme would then become blue for light mode. and you can make it orange for dark mode...

**Comment by DEEPIKA-SUK** [comment]
> @RushanKhan1 you can merge it without it working for mobile view👍
> @DEEPIKA-SUK But I was thinking that should we make the scrollbar fully blue for light mode ? and fully orange for dark mode ?
> 
> In light mode only search button is orange and that too is going to be changed to blue very soon after the PR for it gets merged. So the whole theme would then become blue for light mode. and you can make it orange for dark mode...

As scrollbar does not have the property supported for all browsers to have dark and light mode, I have chosen this color scheme for scrollbar because its matching with both header and body and its looking good if we also remove orange color for search button in light mode.  I think its looking good in both dark and light mode.

**Comment by DEEPIKA-SUK** [comment]
@Pranav016 @RushanKhan1 Kindly merge my PR.

**Comment by Pranav016** [comment]
> @Pranav016 @RushanKhan1 Kindly merge my PR.

Okay @RushanKhan1 will merge it tomorrow after the conflicts have been resolved 👍

**Review by Pranav016 — APPROVED** [review]

**Pull request merged**
