### PR TITLE
Update README gif

### PR DESCRIPTION
**Pull request by innovation-platform**
## What is the change?
I have changed the previous readme gif and placed the gif showing the current features of the website.

## Related issue?
close: #628 
## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Did you lint your code before making the Pull Request?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:

blogsitegiff

### CODE REVIEW

**Comment by Pranav016** [comment]
I feel like the dashboard and edit profile features weren't shown.

**Comment by innovation-platform** [comment]
Ok. I will update it. Thank You.

**Comment by innovation-platform** [comment]
I am working on adding the dashboard and edit profile features to the gif. I will make a commit asap.

**Comment by innovation-platform** [comment]
Should I work on creating new gif showing the dashboard and edit profile or this commit is fine. 
Thank You.

**Comment by Pranav016** [comment]
> Should I work on creating new gif showing the dashboard and edit profile or this commit is fine.
> Thank You.

I think I merged it by mistake, sorry.
Yes you can make a new gif.

**Comment by innovation-platform** [comment]
Ok. I will do it. Thank you.

**Pull request merged**
