### PR TITLE
add-styling-t-contact-us-page(#308)

### PR DESCRIPTION
**Pull request by ankitaugale23**
solves #308

## What is the change?
Add styling and animation to Contact Us page.

## Related issue?
close: #[308]

## How was it tested?
By running the server on localhost

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
[https://drive.google.com/file/d/1PE-tpHXo0_4k64xUmwH7W2MN8kOg1Bcw/view?usp=sharing](url)

### CODE REVIEW

**Review by RushanKhan1 — CHANGES_REQUESTED** [review]
Hey @ankitaugale23, please change the base branch of your pr to ``develop``. Here's how you can do that:

baseBranch

**Comment by RushanKhan1** [comment]
I reviewed your pr and it works as expected. good job!
It looks good to merge except for the changes to the ``package-lock.json`` file.

**Comment by Pranav016** [comment]
> I reviewed your pr and it works as expected. good job!
> It looks good to merge except for the changes to the `package-lock.json` file.

Great, add ready-to-merge label whenever you feel its good to merge. Then I'll review that pr first 🙂

**Comment by Pranav016** [comment]
/gssoc/

/level2/

**Comment by Pranav016** [comment]
/level2/

**Comment by ankitaugale23** [comment]
Would you mind telling me what I have done wrong? @

> I reviewed your pr and it works as expected. good job!
> It looks good to merge except for the changes to the `package-lock.json` file.

I have changed the base branch. I didn't get what are the changes I need to in package-lock.json. Would you mind elaborating on it?

**Comment by RushanKhan1** [comment]
@ankitaugale23 We want everyone working on the project to install the exact same version of all the dependencies to minimize chances of errors, that's why we use a ``package-lock.json``. Changes in ``package-lock.json`` might cause errors later but it's not necessary that they will therefore please try not to modify the file next time while making a pr.

**Comment by RushanKhan1** [comment]
Also, pull request #354 has been merged and that directly modifies the contact us page, hence the merge conflicts. So I suggest you update your fork and look into the changes made by that pr and then update your code according to that. So please make a new pr and close this one.

**Comment by ankitaugale23** [comment]
> Also, pull request #354 has been merged and that directly modifies the contact us page, hence the merge conflicts. So I suggest you update your fork and look into the changes made by that pr and then update your code according to that. So please make a new pr reflecting the changes and close this one.

Sure. I will do that.

**Comment by ankitaugale23** [comment]
I have removed the conflicts but facing an error in the file on which I am not working on (App.js).
Attaching the error here:
`D:\web\BlogSite\app.js:55
const Blog = new mongoose.model("Blog", blogSchema);
      ^

SyntaxError: Identifier 'Blog' has already been declared
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
[nodemon] app crashed - waiting for file changes before starting...`
Kindly check @RushanKhan1

**Comment by Pranav016** [comment]
> I have removed the conflicts but facing an error in the file on which I am not working on (App.js).
> Attaching the error here:
> `D:\web\BlogSite\app.js:55
> const Blog = new mongoose.model("Blog", blogSchema);
> ^
> 
> SyntaxError: Identifier 'Blog' has already been declared
> at wrapSafe (internal/modules/cjs/loader.js:979:16)
> at Module._compile (internal/modules/cjs/loader.js:1027:27)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
> at Module.load (internal/modules/cjs/loader.js:928:32)
> at Function.Module._load (internal/modules/cjs/loader.js:769:14)
> at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
> at internal/main/run_main_module.js:17:47
> [nodemon] app crashed - waiting for file changes before starting...`
> Kindly check @RushanKhan1

Have you pulled the changes that were made today morning ?

**Comment by ankitaugale23** [comment]
> > I have removed the conflicts but facing an error in the file on which I am not working on (App.js).
> > Attaching the error here:
> > `D:\web\BlogSite\app.js:55
> > const Blog = new mongoose.model("Blog", blogSchema);
> > ^
> > SyntaxError: Identifier 'Blog' has already been declared
> > at wrapSafe (internal/modules/cjs/loader.js:979:16)
> > at Module._compile (internal/modules/cjs/loader.js:1027:27)
> > at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
> > at Module.load (internal/modules/cjs/loader.js:928:32)
> > at Function.Module._load (internal/modules/cjs/loader.js:769:14)
> > at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
> > at internal/main/run_main_module.js:17:47
> > [nodemon] app crashed - waiting for file changes before starting...`
> > Kindly check @RushanKhan1
> 
> Have you pulled the changes that were made today morning ?

Should I pull it from master or develop branch @Pranav016

**Comment by Pranav016** [comment]
> > > I have removed the conflicts but facing an error in the file on which I am not working on (App.js).
> > > Attaching the error here:
> > > `D:\web\BlogSite\app.js:55 const Blog = new mongoose.model("Blog", blogSchema); ^ SyntaxError: Identifier 'Blog' has already been declared at wrapSafe (internal/modules/cjs/loader.js:979:16) at Module._compile (internal/modules/cjs/loader.js:1027:27) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) at Module.load (internal/modules/cjs/loader.js:928:32) at Function.Module._load (internal/modules/cjs/loader.js:769:14) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) at internal/main/run_main_module.js:17:47 [nodemon] app crashed - waiting for file changes before starting...`
> > > Kindly check @RushanKhan1
> > 
> > 
> > Have you pulled the changes that were made today morning ?
> 
> Should I pull it from master or develop branch @Pranav016

You can pull it from master but both branches are in sync right now..

**Comment by ankitaugale23** [comment]
> > > > I have removed the conflicts but facing an error in the file on which I am not working on (App.js).
> > > > Attaching the error here:
> > > > `D:\web\BlogSite\app.js:55 const Blog = new mongoose.model("Blog", blogSchema); ^ SyntaxError: Identifier 'Blog' has already been declared at wrapSafe (internal/modules/cjs/loader.js:979:16) at Module._compile (internal/modules/cjs/loader.js:1027:27) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) at Module.load (internal/modules/cjs/loader.js:928:32) at Function.Module._load (internal/modules/cjs/loader.js:769:14) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) at internal/main/run_main_module.js:17:47 [nodemon] app crashed - waiting for file changes before starting...`
> > > > Kindly check @RushanKhan1
> > > 
> > > 
> > > Have you pulled the changes that were made today morning ?
> > 
> > 
> > Should I pull it from master or develop branch @Pranav016
> 
> You can pull it from master but both branches are in sync right now..

Yup thank you for telling me created a new PR with updated changes. Kindly Check @RushanKhan1 @Pranav016

**Comment by Pranav016** [comment]
> Yup thank you for telling me created a new PR with updated changes. Kindly Check @RushanKhan1 @Pranav016

Don't make a PR now, we'll be reviewing and accepting PRs from tomorrow onwards as we mentioned on the GirlScript channel, the project is under maintenance today and more changes will be made to the code that you need to pull 🙂 
Sorry for the inconvenience

**Comment by ankitaugale23** [comment]
> > Yup thank you for telling me created a new PR with updated changes. Kindly Check @RushanKhan1 @Pranav016
> 
> Don't make a PR now, we'll be reviewing and accepting PRs from tomorrow onwards as we mentioned on the GirlScript channel, the project is under maintenance today and more changes will be made to the code that you need to pull 🙂
> Sorry for the inconvenience

Sure. No issues

**Pull request closed without merging**
