### PR TITLE
Update styles.css

### PR DESCRIPTION
**Pull request by Shivam-Shandilya1**
## What is the change?
Update the styles.css by adding the .btnFrame class to their corresponding btns and remove the inconsistency behaviour of button in home.ejs page.

## Related issue?
close: #576

## How was it tested?
I have tested it by running the home.ejs page in localhost:3000 and inspecting through google developer tools.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.

https://user-images.githubusercontent.com/72553479/113655356-42460a00-96b7-11eb-98c2-66a9b44ebd5c.mp4

### CODE REVIEW

**Comment by Shivam-Shandilya1** [comment]
Please review it.

**Review by Pranav016 — APPROVED** [review]
Merging this for now, next time make PR from a new branch

**Comment by Pranav016** [comment]
/gssoc/

**Comment by Pranav016** [comment]
/level2/

**Pull request merged**
