### PR TITLE
Revamped frontend using React JS

### PR DESCRIPTION
**Pull request by A7abhilash**
## What is the change?
Revamped frontend completely using React JS with framer motion for animations and added the following features:
### Features
1. Post/Edit your blogs
2. Set private or public status for your blogs
3. User Profile Visit
4. Save posts(Bookmark)
5. Likes
6. Alerts(in site)
PS: The display pic of every user is set by default as a common avatar.

### Features that can be added:
1. Comments
2. Upload display pics(profile picture)
3. Friend requests

## Related issue?
#221 and #224 

## How was it tested?
The whole application was tested in local host thoroughly resulting in a bug free environment. 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Have you made corresponding changes to the documentation?
- [] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Some of the screenshots:
[Blogsite Frontend](https://drive.google.com/drive/folders/16XnDI3RD0SWwGJzexLjJWSh1Xv7UKjeU?usp=sharing)

### CODE REVIEW

**Review by Pranav016 — CHANGES_REQUESTED** [review]
* change base branch to develop
* Since almost 45 files were changes, I'd suggest deploy this to heroku and then give me the link so that I can test thoroughly. Even if I deploy it on our review branch `develop` it would stop our workflow if there are any production bugs.
* More than halp of the commit messages are incorrect 
```
cleared minor warnings
fixed minor bug
``` 
are wrong commit messages.
Make them right.

**Comment by Pranav016** [comment]
Closing PR for now. reopen if required

**Comment by A7abhilash** [comment]
> * change base branch to develop
> * Since almost 45 files were changes, I'd suggest deploy this to heroku and then give me the link so that I can test thoroughly. Even if I deploy it on our review branch `develop` it would stop our workflow if there are any production bugs.
> * More than half of the commit messages are incorrect
> 
> ```
> cleared minor warnings
> fixed minor bug
> ```
> 
> are wrong commit messages.
> Make them right.
> 
> * make separate PR if solving more than one issue

Will consider the changes to be made and do a PR again...
#gssoc21

**Pull request closed without merging**
