### PR TITLE
Restrict delete comments to author privilege

### PR DESCRIPTION
**Pull request by Athira2199**
## What is the change?
Restricting the deletion of comments as an author-of-comment only privilege.

## Related issue?
close: #326 

## How was it tested?
Tested the base cases on local environment.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.

### CODE REVIEW

**Comment by Pranav016** [comment]
Only the author of the comment is able to delete the comment or the author of the blog post, I checked the code and I guess it's the author of the comment. Can you just confirm this if I am correct or not ?

**Comment by Athira2199** [comment]
> Only the author of the comment is able to delete the comment or the author of the blog post, I checked the code and I guess it's the author of the comment. Can you just confirm this if I am correct or not ?

yes that's right, I have made the functionality as only the author of the comment can delete his/her comment.

**Comment by Pranav016** [comment]
> > Only the author of the comment is able to delete the comment or the author of the blog post, I checked the code and I guess it's the author of the comment. Can you just confirm this if I am correct or not ?
> 
> yes that's right, I have made the functionality as only the author of the comment can delete his/her comment. @Pranav016

what if that person makes a vulgar comment, is anyone else able to delete that ?

**Comment by Athira2199** [comment]
> > > Only the author of the comment is able to delete the comment or the author of the blog post, I checked the code and I guess it's the author of the comment. Can you just confirm this if I am correct or not ?
> > 
> > 
> > yes that's right, I have made the functionality as only the author of the comment can delete his/her comment. @Pranav016
> 
> what if that person makes a vulgar comment, is anyone else able to delete it then ?

yes , I did think of that scenario, we can add a functionality to flag comments and we could keep a threshold like if flagCount > 5 then mark comment as flagged and we could initiate an automatic deletion or we could notify the admin and have him delete the comment(but currently we do not have an admin panel).

**Comment by Pranav016** [comment]
> > > > Only the author of the comment is able to delete the comment or the author of the blog post, I checked the code and I guess it's the author of the comment. Can you just confirm this if I am correct or not ?
> > > 
> > > 
> > > yes that's right, I have made the functionality as only the author of the comment can delete his/her comment. @Pranav016
> > 
> > 
> > what if that person makes a vulgar comment, is anyone else able to delete it then ?
> 
> yes , I did think of that scenario, we can add a functionality to flag comments and we could keep a threshold like if flagCount > 5 then mark comment as flagged and we could initiate an automatic deletion or we could notify the admin and have him/her delete the comment(but currently we do not have an admin panel). @Pranav016

I feel if the comment gets flagged more than 3 times then it should be deleted, if we are restricting the deletion of comments to the author then we should implement the flag feature simultaneously to tackle that problem..

**Comment by Athira2199** [comment]
> > > > > Only the author of the comment is able to delete the comment or the author of the blog post, I checked the code and I guess it's the author of the comment. Can you just confirm this if I am correct or not ?
> > > > 
> > > > 
> > > > yes that's right, I have made the functionality as only the author of the comment can delete his/her comment. @Pranav016
> > > 
> > > 
> > > what if that person makes a vulgar comment, is anyone else able to delete it then ?
> > 
> > 
> > yes , I did think of that scenario, we can add a functionality to flag comments and we could keep a threshold like if flagCount > 5 then mark comment as flagged and we could initiate an automatic deletion or we could notify the admin and have him/her delete the comment(but currently we do not have an admin panel). @Pranav016
> 
> I feel if the comment gets flagged more than 3 times then it should be deleted. If we are restricting the deletion of comments to the author then we should implement the flag feature simultaneously to tackle that problem..

yes, we can do that. raising flag feature as a separate issue as its more like a new feature. @Pranav016

**Comment by Pranav016** [comment]
> > > > > > Only the author of the comment is able to delete the comment or the author of the blog post, I checked the code and I guess it's the author of the comment. Can you just confirm this if I am correct or not ?
> > > > > 
> > > > > 
> > > > > yes that's right, I have made the functionality as only the author of the comment can delete his/her comment. @Pranav016
> > > > 
> > > > 
> > > > what if that person makes a vulgar comment, is anyone else able to delete it then ?
> > > 
> > > 
> > > yes , I did think of that scenario, we can add a functionality to flag comments and we could keep a threshold like if flagCount > 5 then mark comment as flagged and we could initiate an automatic deletion or we could notify the admin and have him/her delete the comment(but currently we do not have an admin panel). @Pranav016
> > 
> > 
> > I feel if the comment gets flagged more than 3 times then it should be deleted. If we are restricting the deletion of comments to the author then we should implement the flag feature simultaneously to tackle that problem..
> 
> yes, we can do that. raising flag feature as a separate issue as its more like a new feature. @Pranav016 Opened issue : #411

So you can make 2 PRs from different branches when you are done working. Right now I am closing this PR, later you can reopen this PR or make 2 PRs together when you are done working on the flag feature. You can even make a single PR for both but that might reduce the points so I would suggest making 2 PRs.

If you can make the flag feature by tomorrow then I won't close this PR and will merge this when you make the other one..

**Comment by Pranav016** [comment]
Closing PR for now, it is having merge conflicts. You can pull the changes and then open a new PR.

**Comment by Athira2199** [comment]
Okay will do that @Pranav016

**Pull request closed without merging**
