### PR TITLE
file db.js is created inside config and promises is handled with mongoose

### PR DESCRIPTION
**Pull request by abhay27chauhan**
## What is the change?
created a new folder named config and created the file inside it called db.js and put the database connection code inside it.

## Related issue?
close: #320

## How was it tested?
yes i have tested the code

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.

### CODE REVIEW

**Comment by abhay27chauhan** [comment]
why did the check failed ??

**Review by Pranav016 — CHANGES_REQUESTED** [review]
Good work, a couple things
* change base branch to which you are making a PR to as develop instead of master.
* why are there changes made to package-lock
* Can you make the url as dynamic such that for local use it is automatically set to localhost otherwise it stays at `process.env.URL`. (optional) (Also update in README if this change is made)

**Comment by abhay27chauhan** [comment]
i did npm install to generate node_modules and it changes package-lock

**Comment by Pranav016** [comment]
> i did npm install to generate node_modules and it changes package-lock

Ok, I'll check it then. Can you change base branch to develop so that I can merge ?

**Pull request merged**
