### PR TITLE
Sign up and login option added in homepage

### PR DESCRIPTION
**Pull request by Abhinaba006**
## What is the change?
the homepage was missing the login options, if a new user comes then there was no option for login except creating a new post and only then the user is redirected to login page

## Related issue?
issue: #301 

## How was it tested?
frontend related issue, locally tested

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

image

### CODE REVIEW

**Comment by Abhinaba006** [comment]
This issue is solved.

**Review by Pranav016 — CHANGES_REQUESTED** [review]
Good work, squash the commits.
You can follow instructions from this if you want to know how to squash commits - https://github.com/ALPHAVIO/ToDoist/pull/6

**Comment by Pranav016** [comment]
/gssoc/

**Comment by Abhinaba006** [comment]
@Pranav016  sir, I have squashed them, but it is not visible here, I don't know why. In my git log, it is showing it in a single commit but here it is the same as before. Here is the ss.
image

**Comment by Pranav016** [comment]
> @Pranav016 sir, I have squashed them, but it is not visible here, I don't know why. In my git log, it is showing it in a single commit but here it is the same as before. Here is the ss.
> image

Commits were squashed successfully you just forget to remove redundant commit messages during squashing.

**Comment by Pranav016** [comment]
@Abhinaba006 PR looks good to merge, can you resolve merge conflicts

**Comment by Pranav016** [comment]
/level2/

**Review by Pranav016 — CHANGES_REQUESTED** [review]
Commit messages are really bad 
image

Resolve merge conflicts

**Comment by Abhinaba006** [comment]
Sir I am removing this branch and making a new branch to work on this issue, I was having some problem to understand git, I will send a new pr for this issue, I am closing this branch.

**Pull request closed without merging**
