### PR TITLE
autoclose issue if corresponding PR gets merged

### PR DESCRIPTION
**Pull request by Ankita297**
## What is the change?
automatically close issue if it's corresponding PR gets merged.
## Related issue
issue: #235

## How was it tested?
I have tested in my local system 
## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.

### CODE REVIEW

**Review by Pranav016 — COMMENTED** [review]
There was already a file name `close-issue.yml` in `.github/workflows/` but I noticed that the extension on that file is missing that is why you were able to create file of same name. Can you change the name of the action you added or change the name of file already present in the workflow, also can you do me favor and `.yml` extension to it since it was missing?

**Comment by Pranav016** [comment]
/gssoc/

**Comment by Ankita297** [comment]
Sir is it okay now ?

**Pull request merged**
