### PR TITLE
Added Constraints For Username and Password

### PR DESCRIPTION
**Pull request by nikhilgupta2001**
## What is the change?
Remove this line and add a description

## Related issue?
issue: #163

## How was it tested?
I tested it in my local system

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Screenshot from 2021-03-10 01-34-18
Screenshot from 2021-03-10 01-34-32

### CODE REVIEW

**Review by shudhanshu03 — COMMENTED** [review]
@nikhilgupta2001 This issue is already assigned to someone else by @Pranav016 .

**Comment by nikhilgupta2001** [comment]
ok if the assigned person do not respond, then please assign it to me .

**Comment by shudhanshu03** [comment]
@nikhilgupta2001 You can go for other issues . This is done by the person who was assigned . Kindly Close this Issue @Pranav016 .

**Pull request closed without merging**
