### PR TITLE
Fire queen 3010 theme changer

### PR DESCRIPTION
**Pull request by FireQueen-3010**
## What is the change?
Changed the complete color theme of the full website.

## Related issue?
close: #268

## How was it tested?
By viewing it on the local server.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [✔] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [✔] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [✔] Have you made corresponding changes to the documentation?
- [✔] Your submission doesn't break any existing feature.
- [✔] Have you tested the code before submission?

## Screenshots or Video:
[https://drive.google.com/file/d/1dhNBHUcv3CTBioZySONLMEdMDb8bnhfh/view?usp=sharing](url)
[https://drive.google.com/file/d/1q47MaSjyGAlWR0Vsp0UjKlLsf7HUO19v/view?usp=sharing](url)
[https://drive.google.com/file/d/1xuogWVMywd5w2lPl8KP_IoecMLnNwNyf/view?usp=sharing](url)

### CODE REVIEW

**Comment by FireQueen-3010** [comment]
I don't understand why did the check fail. Please guide me @AnanyaNegi

**Comment by AnanyaNegi** [comment]
> 
> 
> I don't understand why did the greetings check fail. Please guide me @AnanyaNegi @Pranav016

Change the base branch from `ALPHAVIO:master` to `ALPHAVIO:develop`. (All code related PRs will have base branch develop.
Screenshot_20210126-095421__01__01
)

**Comment by FireQueen-3010** [comment]
I've changed the base branch, please check.

**Comment by Pranav016** [comment]
Resolve conflicts otherwise it looks good to merge!

**Comment by Pranav016** [comment]
@FireQueen-3010 Can you add an image of the theme you implemented ? actually none of the links you provided is working..

**Comment by FireQueen-3010** [comment]
blogsite - homepage change

https://user-images.githubusercontent.com/59244300/111104307-6447e300-8576-11eb-9cfc-28037ddea8eb.mp4

**Comment by Pranav016** [comment]
> blogsite - homepage change
> 
>  blogsite.new.look.mp4 
> @AnanyaNegi has already reviewed the looks yesterday (on discord) @Pranav016, hope it's to your liking as well, looking forward to the merge! Thank you!

Yes, looks very good.
But I noticed issue in the commit where conflicts were resolved. @AnanyaNegi needs to get it fixed :)

**Comment by FireQueen-3010** [comment]
ok

**Pull request closed without merging**
