### PR TITLE
Adding various security features issue #337

### PR DESCRIPTION
**Pull request by udaymittal7**
Added helmet for security http headers.
Added rate limiter to receive 100 requests per hour from a particular IP address.
Added mongo sanitize for data sanitization against noSQL query injection
Added xss for data sanitization against XSS.

Please review and if any changes required let me know.
Thank you.

For issue #337

### CODE REVIEW

**Comment by AnanyaNegi** [comment]
Hi @udaymittal7 . Do change the base branch from `ALPHAVIO:master` to `ALPHAVIO:develop`.
Screenshot_20210126-095421__01__01

**Comment by udaymittal7** [comment]
@AnanyaNegi Done.

**Comment by udaymittal7** [comment]
@AnanyaNegi How to fix this conflicts? I had them before to but was unable to fix them. Please help.

**Comment by Pranav016** [comment]
Resolve conflicts, otherwise looks good to merge.
Refer to the github documentation to know about resolving conflicts, not going to be that hard :)

**Comment by Aryamanz29** [comment]
> @AnanyaNegi How to fix these conflicts? I had them before to but was unable to fix them. Please help.

Bro just removes the conflict code from `package-lock.json` and `package.json` using your code editor. You may also use GitHub to do that. I have also got the same conflicts on the above files.

 **For ref watch this:**  https://youtu.be/JtIX3HJKwfo

**Comment by AnanyaNegi** [comment]
Conflicts have been resolved now.

**Comment by Pranav016** [comment]
Website build is failing after merging this PR.

**Pull request merged**
