### PR TITLE
Added delete button for comments and functionality such that only authenticated user can comment.

### PR DESCRIPTION
**Pull request by aniketlodh**
## What is the change?
Added Delete button for comments which is visible to all to delete comments.
Added functionality such that only authenticated user can comment
Removed the user name input box in the comments and fetched the username from the database.

## How was it tested?
Tested it on my pc and it works fine.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
https://user-images.githubusercontent.com/55927827/108386842-0b18b800-7233-11eb-9e33-33a873895178.mp4

### CODE REVIEW

**Review by Pranav016 — COMMENTED** [review]
Please don't commit to master, follow contribution guidelines. Make a new branch and after working on it, make a PR to develop.

**Comment by Pranav016** [comment]
This code is giving some error on my local machine, could be my environment. So I wasn't able to test this code locally. Can you tell whether the delete option appears for all the people visiting the website or only the user whose post the comment is on or only to the person who has made the comment.

Ideal would be the delete button should be visible to the owner of the post and the person who has made the comment.

**Comment by aniketlodh** [comment]
Yes, the delete comment button appears to all as of now ( as instructed in the issue) so that vulgar comments can be deleted.

**Comment by Pranav016** [comment]
> Yes, the delete comment button appears to all as of now ( as instructed in the issue) so that vulgar comments can be deleted.

Ok, sounds good. Let's make one change though, to delete a comment, the person needs to be logged in or a registered user.

**Comment by aniketlodh** [comment]
Actually, I have made a new pull request to the develop branch so if it is fine then merge the pull request and raise an issue regarding the change. I'll work on that

**Comment by Pranav016** [comment]
> Actually, I have made a new pull request to the develop branch so if it is fine then merge the pull request and raise an issue regarding the change. I'll work on that

No it is the part of this issue only, regarding deleting a comment. Even if you have created a pull request, you can still make changes to that adding commits to that branch. It's a very small and easy updation. Let me know when you're done.

**Comment by aniketlodh** [comment]
Hi,
I have made the changes and also made a PR on the develop branch.

**Pull request closed without merging**
