### PR TITLE
Added backgrounds

### PR DESCRIPTION
**Pull request by karunkarthik-git**
Signed-off-by: KarunKarthik <kkarun0542@gmail.com>

## What is the change?
Added backgrounds

## Related issue?
issue: #109 

## How was it tested?
Manual testing

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.

### CODE REVIEW

**Comment by Pranav016** [comment]
Tested on different browsers-
This is how it appears

https://user-images.githubusercontent.com/54665036/107518196-be026980-6bd4-11eb-8d39-a31c5165f502.mp4

**Comment by karunkarthik-git** [comment]
Yes I've fixed it kindly check it again

**Review by Pranav016 — CHANGES_REQUESTED** [review]
* ### Some issue with background of home page (tested on multiple browsers)
image

* ### Also I wasn't able to compose any article in your PR, can't find the change that caused that. Also do some testing for that on your local system before making next PR/ commit.

**Comment by karunkarthik-git** [comment]
Yeah I've fixed both of them. Give a check.

**Review by Pranav016 — CHANGES_REQUESTED** [review]
#### Commit messages are incorrect
```
Fixed input bug
Fixed homepage bug
```
If I ever want to rollback to these commits or commits before this then I won't know what bug is being referred to here..
**Kindly squash the commits**

#### Background responsiveness issues-
Either use relative units of measurements (`vh` or `vw`) or media queries.

https://user-images.githubusercontent.com/54665036/107639654-2c0f6500-6c97-11eb-9338-2a1ee4ebf859.mp4

**Comment by karunkarthik-git** [comment]
I was assigned to make backgrounds, the website isn't responsive since
beginning. You can create another issue for it.

**Comment by Pranav016** [comment]
> I was assigned to make backgrounds, the website isn't responsive since beginning. You can create another issue for it.

I agree with you, it's not completely responsive but to some extent it is.. 


https://user-images.githubusercontent.com/54665036/107642061-62021880-6c9a-11eb-8c1f-e5ff490f7cb7.mp4


I think it's your image positing that's causing the issue. You can either fix that or make a new PR to update the background to be a plain color or linear gradient instead of an image.

**Comment by Pranav016** [comment]
Closing this for now, reopen if required.

**Pull request closed without merging**
