### PR TITLE
Added status field

### PR DESCRIPTION
**Pull request by A7abhilash**
## What is the change?
Added status field(private/public) to the blogs allows user to keep some blogs in public or private according to their wish.
This allows user to set save their blogs as draft if set to private status. Only blogs with status set as public will be visible to all users but private ones are gonna be visible for only the author.
**PS: The old blogs(posted before merging this feature) that didn't have the status field (set to either public or private) shall not be displayed. The new blogs that shall be posted with public status will be displayed publicly to everyone.**

## Related issue?
close: #463 

## How was it tested?
Tested the functionality thoroughly in localhost.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.

### CODE REVIEW

**Review by Pranav016 — APPROVED** [review]
LGTM

**Comment by Pranav016** [comment]
Should I clear the database then if older post won't be visible ?

**Comment by A7abhilash** [comment]
> Should I clear the database then if older post won't be visible ?

Yes u can👍

**Comment by Pranav016** [comment]
@A7abhilash I am merging this PR and clearing the DB, add a few good blogs after this so that the website doesn't look empty :p

**Comment by Pranav016** [comment]
/gssoc/

**Comment by Pranav016** [comment]
/level3/

**Pull request merged**
