### PR TITLE
Issue 326

### PR DESCRIPTION
**Pull request by Athira2199**
## What is the change?
Change in Blog model, change in posts.ejs and change in posts router.

## Related issue?
issue: #326

## How was it tested?
Yes, sample inputs were given and the required functionality was tested.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.

### CODE REVIEW

**Comment by Athira2199** [comment]
/gssoc/

**Review by Pranav016 — COMMENTED** [review]
* Work from a new branch, don't commit to master.
* Commit messages are incorrect, either squash commits or redo work on a new branch

**Review by Pranav016 — CHANGES_REQUESTED** [review]
Resolve conflicts
These commit messages are wrong, they should tell what changes you made in that commit
image

**Comment by Athira2199** [comment]
> Resolve conflicts
> These commit messages are wrong, they should tell what changes you made in that commit. You can either squash the commits with a correct commit message or redo the commits on a new branch.
> image

Hi, I have to squash the comments and create a new pull request ?

**Comment by RushanKhan1** [comment]
Hey @Athira2199! Thanks for contributing! Actually, there have been some major changes to the code base to fix the bug that was in production also, there are still some more changes that need to be done therefore please **pull the updated code tomorrow** and make a new pr according to that else there will be a lot of merge conflicts.

**Pull request closed without merging**
