### PR TITLE
Added Issue templates

### PR DESCRIPTION
**Pull request by uttu2**
Added issue templates.

### CODE REVIEW

**Comment by Pranav016** [comment]
Great work

**Comment by Pranav016** [comment]
@all-contributors please add @uttu2 for doc

**Comment by Pranav016** [comment]
@all-contributors please add @uttu2 for doc

**Comment by Pranav016** [comment]
@uttu2 You contributed as a part of JWoC right? Please respond on the discord channel or comment down your full name here.

**Comment by uttu2** [comment]
Yes. Utkarsh Tyagi

**Pull request merged**
