### PR TITLE
Add directories to store Models and Routes

### PR DESCRIPTION
**Pull request by Abhinaba006**
## What is the change?
I have remove the blog model and the routes from app.js and place them under the correct directory, now the code is clean and ready for further development.

## Related issue?
issue: #282 

## How was it tested?
I have tested on my pc locally on localhost, all its functionality is working fine.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
[VIdeo](https://drive.google.com/file/d/1pwA1wdbU6IVCCwtgckkgc6YO0nPUj6Qh/view?usp=sharing)

### CODE REVIEW

**Review by Pranav016 — CHANGES_REQUESTED** [review]
* Update PR headline
* Update your last commit message. Run these commands
```
git commit --amend -m "Add directories to store Models and Routes"
git push origin <branch-name> -f
```

**Comment by Abhinaba006** [comment]
the changes were made as requested.

**Comment by Pranav016** [comment]
@Abhinaba006 Reviewed the code, looks good and ready to be merged. The demo video you added is restricted (I am guessing on google drive) Can you add an open link or just add the video in chat, GitHub now allows that

**Comment by Abhinaba006** [comment]
Yes, the permission was restricted, now it 
should be visible httpss://drive.google.com/file/d/1pwA1wdbU6IVCCwtgckkgc6YO0nPUj6Qh/view?usp=drivesdk

**Comment by Abhinaba006** [comment]
Video

**Comment by Abhinaba006** [comment]
[video](https://drive.google.com/file/d/1pwA1wdbU6IVCCwtgckkgc6YO0nPUj6Qh/view)

**Comment by Pranav016** [comment]
@Abhinaba006 After merging this PR, when I click on READ More on any post it gives error!

**Comment by prajjwalarora** [comment]
@Pranav016  I have a doubt as this PR changing the code structure and using still postName for post endpoints but my PR #264  still not merged that fixed postName related issue and using the old code structure. that will not create a conflict?

**Comment by Pranav016** [comment]
> @Pranav016 I have a doubt as this PR changing the code structure and using still postName for post endpoints but my PR #264 still not merged that fixed postName related issue and using the old code structure. that will not create a conflict?

Yes, It can give conflicts. 
I'd suggest you pull the changes and work on a new branch or work on the same branch and squash the commits.

**Comment by prajjwalarora** [comment]
> > @Pranav016 I have a doubt as this PR changing the code structure and using still postName for post endpoints but my PR #264 still not merged that fixed postName related issue and using the old code structure. that will not create a conflict?
> 
> Yes, It can give conflicts.
> I'd suggest you pull the changes and work on a new branch or work on the same branch and squash the commits.

ok thanks, I pull changes and work on the same branch. I think that will update PR as well as I commit to that branch

**Pull request merged**
