### PR TITLE
Improved website to Responsive

### PR DESCRIPTION
**Pull request by pankajkumarbij**
## What is the change?
All hard code is changed into responsive code.

## Related issue?
issue: #177 

## How was it tested?
I have tested it in my local system.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:

https://user-images.githubusercontent.com/59636849/108155011-13260a00-7104-11eb-88a1-3a8765fbab68.mp4

### CODE REVIEW

**Review by Pranav016 — CHANGES_REQUESTED** [review]
Good work, some changes-

* Change base branch to develop.
* There is some issue with the footer in mobile view, doesn't show the full footer on different screen sizes. Could be on my local machine but please check ones.

https://user-images.githubusercontent.com/54665036/108332040-61ff9c80-71f5-11eb-9417-e72656ec9794.mp4


* Dark mode button not placed correctly at the bottom in dark mode. It covers the copyright text (mobile view)

Screenshot 2021-02-18 142610

* Navbar-brand/ the logo text is not responsive so it pushes the navbar menu button down. (mobile view)

Screenshot 2021-02-18 140633

* Navbar menu button should be on the right/ right aligned. (this is in tablet view) 

Screenshot 2021-02-18 141005

* Navbar needs some padding and alignment, giving issue in this view.

Screenshot 2021-02-18 141535

**Comment by Pranav016** [comment]
@pankajkumarbij still working on this or can I close this PR?

**Comment by pankajkumarbij** [comment]
> @pankajkumarbij still working on this or can I close this PR?

I will do required changes by end of the today.
Actually I was busy in collage exams.

**Comment by pankajkumarbij** [comment]
I have close this PR and Make a new updated PR.

**Pull request closed without merging**
