### PR TITLE
login and signup button added

### PR DESCRIPTION
**Pull request by Abhinaba006**
## What is the change?
Remove this line and add a description

## Related issue?
close: #301 
## How was it tested?
locally

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.
image

### CODE REVIEW

**Review by Pranav016 — COMMENTED** [review]
Good work, looks good to merge. A couple of things-
* I am skeptical about the changes in package-lock.json but we'll check after merging if its giving any error.
* Change base branch to develop

**Comment by Pranav016** [comment]
/gssoc/

**Comment by Pranav016** [comment]
/level2/

**Comment by Pranav016** [comment]
/gssoc/

**Comment by AnanyaNegi** [comment]
@Abhinaba006 there are a lot of conflicts in the `styles.css` file. Do resolve them. Otherwise code looks good to go.

**Comment by Abhinaba006** [comment]
@AnanyaNegi , please check, all the conflicts are resolved

**Comment by RushanKhan1** [comment]
Hey @Abhinaba006! Thanks for contributing! Actually, there have been some major changes to the code base to fix the bug that was in production also, there are still some more changes that need to be done therefore please **pull the updated code tomorrow** and make a new pr according to that else there will be a lot of merge conflicts.

**Pull request closed without merging**
