### PR TITLE
Added update option on each post.

### PR DESCRIPTION
**Pull request by aniketlodh**
## What is the change?
Added Edit button to update each post and author-only authorization to edit the posts also added.
## Related issue?
close: #228 

## How was it tested?
Tested the app on my local machine and it worked perfectly

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Have you tested the code before submission?

## Screenshots or Video:
https://user-images.githubusercontent.com/55927827/111677751-862ab980-8845-11eb-9d32-ac719b006c35.mp4

### CODE REVIEW

**Comment by Pranav016** [comment]
As we said on the BlogSite channel on GirlScript server that the code will be under maintenance till today, so we weren't accepting any PRs till now. There were some major code changes therefore I request you to pull all the changes and make a new PR to maintain consistency..
Sorry for inconvenience 🙂

**Comment by aniketlodh** [comment]
Okay @Pranav016, I appreciate the hard work you guys are doing. Will generate a new PR tomorrow.

**Comment by Pranav016** [comment]
> Okay @Pranav016, I appreciate the hard work you guys are doing. Will generate a new PR tomorrow.

Thank you, I appreciate your hard work as well 🙂

**Comment by aniketlodh** [comment]
So can I generate a new PR now?

**Comment by Pranav016** [comment]
> So should I generate a new PR now?

Yes, you can make the PR anytime you want now

**Pull request closed without merging**
