### PR TITLE
Added functionality to search by title on the home page

### LINKED ISSUE #14: Add functionality to search articles by title on the home page.

### PR DESCRIPTION
**Pull request by sahilsaha7773**
Fixes #14

### CODE REVIEW

**Comment by Pranav016** [comment]
Please resolve merge conflicts and add a demo video/ screen recording of the working of the feature that you implemented.

**Comment by sahilsaha7773** [comment]
Here is the demo 
search_functionality

**Comment by Pranav016** [comment]
Excellent work @sahilsaha7773 . There are a couple of redundant commits/ extra commits that are not required. We always have to make sure to keep the commit history clean. If you know how to squash the 3 commits together then please do it or else let me know I'll help.

**Comment by Pranav016** [comment]
The commits have actually doubled. Let me tell you a trick if you are not able to squash.
image


Just copy app.js and home.ejs file that you added the code to. Go back to master, make a new branch.
Now replace the app.js and home.ejs file with the ones you copied and make a PR, your job will get done in just 1 commit.
Happy Learning!

Ask freely in case of any queries.

**Comment by sahilsaha7773** [comment]
This commit history got pretty messed up here, am openining another PR from a different branch, thanks!

**Pull request closed without merging**
